# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26b2146d253224b796fb269fbd050b70c8b4503370ae9b48ae84ecbc6679532ab7e21de78af9c979dce2ed5d20211dc202b849be45e86aae2ec5bd7e351c67f9

test:
  secret_key_base: 8d9d9cff039703cc9b89498218f18a56a47123df062a668bfc9f98c819e2312049cd33eb4fd516671b9baea626820a60fe82694e0dc3cf830324c06d4dd9d166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
